'use client'

export const dynamic = 'force-dynamic'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import AppShell from '../../components/app-shell'
import { createClient } from '../../supabase-client'
import './journal.module.css'

type Entry={id:string;user_id:string;title:string;content:string|null;reference_at:string|null;tags:string[]|null;created_at:string;updated_at:string}
export default function JournalPage(){const router=useRouter();const supabase=useMemo(()=>createClient(),[]);const [entries,setEntries]=useState<Entry[]>([]);const [userId,setUserId]=useState('');const [email,setEmail]=useState('');const [search,setSearch]=useState('');const [tag,setTag]=useState('');const [selected,setSelected]=useState<Entry|null>(null);const [form,setForm]=useState({title:'',content:'',reference_at:'',tags:''});const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [mobileEditor,setMobileEditor]=useState(false)
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}setUserId(user.id);setEmail(user.email??'');const {data,error:e}=await supabase.from('journal_entries').select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(e)setError(e.message);setEntries((data??[]) as Entry[])}useEffect(()=>{load()},[])
 const tags=useMemo(()=>Array.from(new Set(entries.flatMap(e=>e.tags??[]))).sort(),[entries]);const filtered=useMemo(()=>entries.filter(e=>{const q=search.trim().toLowerCase();const matches=!q||e.title.toLowerCase().includes(q)||(e.content??'').toLowerCase().includes(q);const matchesTag=!tag||((e.tags??[]).includes(tag));return matches&&matchesTag}),[entries,search,tag])
 function newEntry(){setSelected(null);setForm({title:'',content:'',reference_at:'',tags:''});setError('');setMobileEditor(true)}function edit(e:Entry){setSelected(e);setForm({title:e.title,content:e.content??'',reference_at:e.reference_at?new Date(e.reference_at).toISOString().slice(0,16):'',tags:(e.tags??[]).join(', ')});setError('');setMobileEditor(true)}
 async function save(ev:FormEvent){ev.preventDefault();if(!form.title.trim()){setError('Informe um título.');return}setSaving(true);setError('');const tags=form.tags.split(',').map(x=>x.trim()).filter(Boolean);const payload={title:form.title.trim(),content:form.content,reference_at:form.reference_at?new Date(form.reference_at).toISOString():null,tags};const result=selected?await supabase.from('journal_entries').update(payload).eq('id',selected.id).eq('user_id',userId):await supabase.from('journal_entries').insert({...payload,user_id:userId});if(result.error)setError(result.error.message);else{await load();setSelected(null);setForm({title:'',content:'',reference_at:'',tags:''});setMobileEditor(false)}setSaving(false)}
 async function remove(){if(!selected)return;if(!window.confirm('Excluir esta nota?'))return;setSaving(true);const {error:e}=await supabase.from('journal_entries').delete().eq('id',selected.id).eq('user_id',userId);if(e)setError(e.message);else{await load();setSelected(null);setForm({title:'',content:'',reference_at:'',tags:''});setMobileEditor(false)}setSaving(false)}
 return <AppShell email={email}><div className="page"><div className="eyebrow">Espaço pessoal</div><div className="toolbar"><div><h1>Meu Journal</h1><p className="sub">Suas anotações pessoais. Só você pode acessá-las.</p></div><button className="btn primary" onClick={newEntry}>+ Nova nota</button></div>{error&&<div className="form-error">{error}</div>}<div className={`journal-layout ${mobileEditor?'editor-mode':''}`}><section className="card journal-list"><div className="journal-list-head"><input placeholder="Buscar notas..." value={search} onChange={e=>setSearch(e.target.value)}/>{tags.length>0&&<div className="journal-tags"><button className={`journal-tag ${!tag?'active':''}`} onClick={()=>setTag('')}>Todas</button>{tags.map(t=><button key={t} className={`journal-tag ${tag===t?'active':''}`} onClick={()=>setTag(t)}>{t}</button>)}</div>}</div><div className="journal-items">{filtered.map(e=><button className={`journal-item ${selected?.id===e.id?'active':''}`} key={e.id} onClick={()=>edit(e)}><strong>{e.title}</strong><small>{new Date(e.created_at).toLocaleString('pt-BR')}</small><p>{e.content||'Sem conteúdo'}</p></button>)}{!filtered.length&&<div className="empty">Nenhuma nota encontrada.</div>}</div></section><section className="card journal-editor">{selected||mobileEditor?<><div className="journal-editor-head"><div><h2>{selected?'Editar nota':'Nova nota'}</h2><div className="journal-meta">{selected?`Criada em ${new Date(selected.created_at).toLocaleString('pt-BR')}`:'Rascunho pessoal'}</div></div><button className="btn journal-new-mobile" type="button" onClick={()=>setMobileEditor(false)}>Voltar</button></div><form onSubmit={save}><label>Título<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Conteúdo<textarea value={form.content} onChange={e=>setForm({...form,content:e.target.value})} placeholder="Escreva aqui..."/></label><label>Data/hora de referência (opcional)<input type="datetime-local" value={form.reference_at} onChange={e=>setForm({...form,reference_at:e.target.value})}/></label><label>Tags <span className="journal-meta">separe por vírgulas</span><input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="cliente, reunião, pessoal"/></label><div className="modal-actions"><button type="button" className="btn" onClick={()=>{setSelected(null);setForm({title:'',content:'',reference_at:'',tags:''});setMobileEditor(false)}}>Cancelar</button>{selected&&<button type="button" className="btn danger" onClick={remove}>Excluir</button>}<button className="btn primary" disabled={saving}>{saving?'Salvando...':'Salvar nota'}</button></div></form></>:<div className="journal-empty">Selecione uma nota ou crie uma nova para começar.</div>}</section></div></div></AppShell>}
