'use client'

import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import AppShell from '../../components/app-shell'
import { createClient } from '../../supabase-client'

type Lead={id:string;nome:string;telefone:string|null;email:string|null;responsavel_id:string|null}
type Template={id:string;nome:string;tipo:string;descricao:string|null;file_path:string;file_name:string;file_size:number|null;extracted_text:string;created_at:string}
type Document={id:string;lead_id:string;template_id:string|null;nome:string;tipo:string;content_html:string;file_path:string|null;file_name:string|null;created_by:string|null;created_at:string;updated_at:string}
const types=['Compra e venda','Promessa de compra e venda','Reserva / sinal','Locação','Procuração','Declaração','Financiamento','Outro']
const fields=[['NOME_CLIENTE','Nome do cliente'],['TELEFONE','Telefone'],['EMAIL','E-mail'],['DATA','Data atual']]
function extractText(text:string){return text.replace(/\s+/g,' ').trim()}
async function readPdf(file:File){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let text='';for(let i=1;i<=Math.min(pdf.numPages,40);i++){const page=await pdf.getPage(i);const content=await page.getTextContent();text+=' '+content.items.map((x:any)=>'str' in x?x.str:'').join(' ')}return extractText(text)}
function escapeHtml(s:string){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;')}
function fillTemplate(text:string,lead:Lead){const date=new Date().toLocaleDateString('pt-BR');return text.replace(/\{\{\s*NOME_CLIENTE\s*\}\}/gi,lead.nome).replace(/\{\{\s*TELEFONE\s*\}\}/gi,lead.telefone||'').replace(/\{\{\s*EMAIL\s*\}\}/gi,lead.email||'').replace(/\{\{\s*DATA\s*\}\}/gi,date)}
function htmlFromText(text:string){return escapeHtml(text).replace(/\n/g,'<br>')}
export default function ContratosPage(){const router=useRouter();const supabase=useMemo(()=>createClient(),[]);const[role,setRole]=useState('corretor');const[userId,setUserId]=useState('');const[leads,setLeads]=useState<Lead[]>([]);const[templates,setTemplates]=useState<Template[]>([]);const[documents,setDocuments]=useState<Document[]>([]);const[templateFile,setTemplateFile]=useState<File|null>(null);const[templateText,setTemplateText]=useState('');const[templateForm,setTemplateForm]=useState({nome:'',tipo:'Compra e venda',descricao:''});const[leadId,setLeadId]=useState('');const[templateId,setTemplateId]=useState('');const[docName,setDocName]=useState('');const[docType,setDocType]=useState('Compra e venda');const[editor,setEditor]=useState('');const[editingDoc,setEditingDoc]=useState<Document|null>(null);const[search,setSearch]=useState('');const[processing,setProcessing]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}setUserId(user.id);setLeadId(new URLSearchParams(window.location.search).get('lead')||'');const{data:p}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();setRole(p?.role??'corretor');const[{data:t,error:te},{data:l,error:le},{data:d,error:de}]=await Promise.all([supabase.from('contract_templates').select('*').order('created_at',{ascending:false}),supabase.from('leads').select('id,nome,telefone,email,responsavel_id').is('deleted_at',null).order('nome').limit(3000),supabase.from('contract_documents').select('*').order('updated_at',{ascending:false}).limit(1000)]);if(te||le||de)setError((te||le||de)?.message||'Não foi possível carregar contratos.');setTemplates((t??[])as Template[]);setLeads((l??[])as Lead[]);setDocuments((d??[])as Document[]) }
useEffect(()=>{load()},[])
async function chooseTemplateFile(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(f.type!=='application/pdf'){setError('O modelo deve ser um PDF.');return}setProcessing(true);setError('');setTemplateFile(f);try{const text=await readPdf(f);setTemplateText(text);setTemplateForm(v=>({...v,nome:v.nome||f.name.replace(/\.pdf$/i,'').replace(/[-_]+/g,' ')}));setMessage(text?'PDF lido. Use {{NOME_CLIENTE}}, {{TELEFONE}}, {{EMAIL}} e {{DATA}} no modelo para preenchimento automático.':'O PDF não possui texto selecionável. Um modelo escaneado não pode ser convertido automaticamente em texto editável.')}catch{setError('Não foi possível ler o PDF. Prefira um PDF com texto selecionável.')}setProcessing(false)}
async function saveTemplate(){if(role!=='admin'&&role!=='gerente')return;if(!templateFile||!templateForm.nome.trim()){setError('Informe o nome e selecione o PDF do contrato.');return}if(!templateText.trim()){setError('O PDF precisa conter texto selecionável para ser usado como modelo editável.');return}setProcessing(true);setError('');const path=`${crypto.randomUUID()}-${templateFile.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const{error:ue}=await supabase.storage.from('contract-templates').upload(path,templateFile,{contentType:'application/pdf'});if(ue){setError(ue.message);setProcessing(false);return}const{error:ie}=await supabase.from('contract_templates').insert({nome:templateForm.nome.trim(),tipo:templateForm.tipo,descricao:templateForm.descricao.trim()||null,file_path:path,file_name:templateFile.name,file_size:templateFile.size,extracted_text:templateText,uploaded_by:userId});if(ie){await supabase.storage.from('contract-templates').remove([path]);setError(ie.message)}else{setTemplateFile(null);setTemplateText('');setTemplateForm({nome:'',tipo:'Compra e venda',descricao:''});setMessage('Modelo de contrato cadastrado.');await load()}setProcessing(false)}
function startDocument(){const lead=leads.find(l=>l.id===leadId);const t=templates.find(x=>x.id===templateId);if(!lead||!t){setError('Selecione o cliente e o modelo de contrato.');return}setEditingDoc(null);setDocType(t.tipo);setDocName(`${t.nome} - ${lead.nome}`);setEditor(fillTemplate(t.extracted_text,lead));setError('');window.scrollTo({top:0,behavior:'smooth'})}
function editDocument(d:Document){setEditingDoc(d);setLeadId(d.lead_id);setDocType(d.tipo);setDocName(d.nome);setEditor(d.content_html.replace(/<br>/g,'\n').replace(/<[^>]+>/g,''));window.scrollTo({top:0,behavior:'smooth'})}
async function saveDocument(){const lead=leads.find(l=>l.id===leadId);if(!lead||!editor.trim()||!docName.trim()){setError('Selecione um cliente e preencha o contrato.');return}setProcessing(true);setError('');const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${escapeHtml(docName)}</title><style>body{font-family:Arial,sans-serif;max-width:850px;margin:40px auto;line-height:1.55;color:#111;padding:0 32px} @media print{body{margin:20mm auto;max-width:none;padding:0}}</style></head><body>${htmlFromText(editor)}</body></html>`;const path=`${lead.id}/${crypto.randomUUID()}.html`;const{error:ue}=await supabase.storage.from('contract-documents').upload(path,new Blob([html],{type:'text/html'}),{contentType:'text/html',upsert:false});if(ue){setError(ue.message);setProcessing(false);return}const payload={lead_id:lead.id,template_id:editingDoc?.template_id||templateId||null,nome:docName.trim(),tipo:docType,content_html:html,file_path:path,file_name:`${docName.trim().replace(/[^a-zA-Z0-9._-]/g,'_')}.html`,created_by:editingDoc?.created_by||userId,updated_by:userId};const result=editingDoc?await supabase.from('contract_documents').update(payload).eq('id',editingDoc.id):await supabase.from('contract_documents').insert(payload);if(result.error){await supabase.storage.from('contract-documents').remove([path]);setError(result.error.message)}else{setMessage('Contrato salvo na pasta do cliente.');setEditingDoc(null);setEditor('');setDocName('');await load()}setProcessing(false)}
async function openStored(d:Document){if(!d.file_path)return;const{data,error}=await supabase.storage.from('contract-documents').createSignedUrl(d.file_path,3600);if(error||!data?.signedUrl){setError(error?.message||'Não foi possível abrir o contrato.');return}window.open(data.signedUrl,'_blank','noopener,noreferrer')}
function printDocument(){if(!editor.trim())return;const w=window.open('','_blank');if(!w)return;w.document.write(`<!doctype html><html><head><title>${escapeHtml(docName||'Contrato')}</title><style>body{font-family:Arial,sans-serif;max-width:850px;margin:40px auto;line-height:1.55;font-size:14px}@media print{body{margin:20mm auto}}</style></head><body>${htmlFromText(editor)}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250)}
const canManage=role==='admin'||role==='gerente';const visibleLeads=leads.filter(l=>{const q=search.toLowerCase().trim();return!q||l.nome.toLowerCase().includes(q)||(l.telefone||'').includes(q)||(l.email||'').toLowerCase().includes(q)});const leadName=(id:string)=>leads.find(l=>l.id===id)?.nome||'Cliente';return <AppShell role={role}><div className="page"><div className="eyebrow">Documentação comercial</div><h1>Contratos</h1><p className="sub">Modelos padrão da imobiliária e contratos preenchidos vinculados à pasta de cada cliente.</p>{message&&<div className="form-success">{message}</div>}{error&&<div className="form-error">{error}</div>}{canManage&&<section className="card"><h2 className="section-title">Modelos padrão</h2><p className="sub">Gerente e admin podem cadastrar PDFs. Para preenchimento automático, coloque no texto do modelo: {fields.map(([k])=>`{{${k}}}`).join(', ')}.</p><div className="lead-form"><div className="form-grid"><label>Nome do modelo *<input value={templateForm.nome} onChange={e=>setTemplateForm({...templateForm,nome:e.target.value})}/></label><label>Tipo<select value={templateForm.tipo} onChange={e=>setTemplateForm({...templateForm,tipo:e.target.value})}>{types.map(t=><option key={t}>{t}</option>)}</select></label></div><label>Descrição<input value={templateForm.descricao} onChange={e=>setTemplateForm({...templateForm,descricao:e.target.value})} placeholder="Ex.: contrato padrão usado nas vendas MCMV"/></label><label>PDF do contrato *<input type="file" accept="application/pdf" onChange={chooseTemplateFile} disabled={processing}/></label>{templateFile&&<div className="sub">{templateFile.name} · {(templateFile.size/1024/1024).toFixed(1)} MB</div>}<button className="btn primary" onClick={saveTemplate} disabled={processing}>{processing?'Processando...':'Cadastrar modelo'}</button></div></section>}
<section className="card"><div className="toolbar"><div><h2 className="section-title">Novo contrato preenchido</h2><p className="sub">Selecione o cliente, escolha o modelo e edite o texto antes de salvar.</p></div></div><div className="form-grid"><label>Pesquisar cliente<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome, telefone ou e-mail"/></label><label>Cliente<select value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">Selecione...</option>{visibleLeads.map(l=><option key={l.id} value={l.id}>{l.nome}{l.telefone?` · ${l.telefone}`:''}</option>)}</select></label><label>Modelo<select value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">Selecione...</option>{templates.map(t=><option key={t.id} value={t.id}>{t.nome} · {t.tipo}</option>)}</select></label></div><div className="modal-actions"><button className="btn primary" onClick={startDocument}>Carregar modelo para edição</button></div>{editor&&<div style={{marginTop:20}}><div className="form-grid"><label>Nome do documento<input value={docName} onChange={e=>setDocName(e.target.value)}/></label><label>Tipo<select value={docType} onChange={e=>setDocType(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></label></div><label style={{display:'grid',gap:7,marginTop:14,fontSize:13,fontWeight:700}}>Contrato editável<textarea rows={24} value={editor} onChange={e=>setEditor(e.target.value)} style={{width:'100%',padding:16,border:'1px solid #d7dbe2',borderRadius:8,lineHeight:1.6,resize:'vertical'}}/></label><div className="modal-actions"><button className="btn" onClick={printDocument}>Imprimir / Salvar PDF</button><button className="btn primary" onClick={saveDocument} disabled={processing}>{processing?'Salvando...':'Salvar na pasta do cliente'}</button></div></div>}</section>
<section className="card"><div className="toolbar"><div><h2 className="section-title">Pasta de contratos</h2><p className="sub">Documentos preenchidos ficam vinculados ao cliente e podem ser reabertos para edição.</p></div></div>{documents.length===0?<div className="empty">Nenhum contrato preenchido ainda.</div>:<div className="table-wrap"><table><thead><tr><th>Cliente</th><th>Contrato</th><th>Tipo</th><th>Atualizado</th><th>Ações</th></tr></thead><tbody>{documents.map(d=><tr key={d.id}><td><strong>{leadName(d.lead_id)}</strong></td><td>{d.nome}</td><td><span className="status blue">{d.tipo}</span></td><td>{new Date(d.updated_at).toLocaleString('pt-BR')}</td><td><div className="actions"><button className="btn" onClick={()=>editDocument(d)}>Editar</button><button className="btn" onClick={()=>openStored(d)}>Baixar / abrir</button></div></td></tr>)}</tbody></table></div>}</section></div></AppShell>}
