import crypto from 'node:crypto'
import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const graphVersion = process.env.META_GRAPH_API_VERSION
const pageToken = process.env.META_PAGE_ACCESS_TOKEN

function serviceClient(){
  const url=process.env.NEXT_PUBLIC_SUPABASE_URL; const key=process.env.SUPABASE_SERVICE_ROLE_KEY
  if(!url||!key) throw new Error('Servidor sem credenciais administrativas do Supabase.')
  return createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}})
}
function fieldObject(value:any){const out:Record<string,string>={};if(Array.isArray(value))for(const item of value){const name=String(item?.name??'').trim();if(name)out[name]=Array.isArray(item?.values)?String(item.values[0]??''):String(item?.values??'')}return out}
async function graphGet(id:string,fields:string){if(!graphVersion||!pageToken)return null;const url=new URL('https://graph.facebook.com/'+graphVersion+'/'+id);url.searchParams.set('fields',fields);url.searchParams.set('access_token',pageToken);const res=await fetch(url.toString(),{cache:'no-store'});if(!res.ok)throw new Error('Meta Graph API respondeu '+res.status+': '+await res.text());return res.json()}
function firstField(fields:Record<string,string>,names:string[]){for(const name of names){const hit=Object.entries(fields).find(([key])=>key.toLowerCase().replace(/[^a-z0-9]/g,'')===name.toLowerCase().replace(/[^a-z0-9]/g,''));if(hit)return hit[1]}return ''}
async function processLead(value:any){
 const supabase=serviceClient(); const leadgenId=String(value?.leadgen_id??value?.id??''); if(!leadgenId)return{status:'ignored',reason:'leadgen_id ausente'}
 const existingMeta=await supabase.from('meta_leads').select('id,lead_id').eq('meta_lead_id',leadgenId).maybeSingle(); if(existingMeta.data)return{status:'duplicate',leadId:existingMeta.data.lead_id}
 let leadData=value; if(value?.leadgen_id&&pageToken&&graphVersion){const fetched=await graphGet(leadgenId,'id,created_time,field_data,ad_id,adset_id,form_id,platform');if(fetched)leadData={...value,...fetched}}
 const fields=fieldObject(leadData?.field_data); const name=firstField(fields,['full_name','nome','name','nome_completo','nomecompleto'])||String(leadData?.nome??''); const phone=firstField(fields,['phone_number','phone','telefone','celular','whatsapp'])||String(leadData?.telefone??''); const email=firstField(fields,['email','e-mail'])||String(leadData?.email??'')
 const campaignId=String(leadData?.campaign_id??leadData?.campaign?.id??''); const adsetId=String(leadData?.adset_id??leadData?.adset?.id??''); const adId=String(leadData?.ad_id??''); const formId=String(leadData?.form_id??''); const pageId=String(leadData?.page_id??'')
 let campaignName=String(leadData?.campaign_name??leadData?.campaign?.name??''); let adsetName=String(leadData?.adset_name??leadData?.adset?.name??''); let adName=String(leadData?.ad_name??''); let formName=String(leadData?.form_name??'')
 if(adId&&pageToken&&graphVersion){try{const ad=await graphGet(adId,'id,name,adset{id,name},campaign{id,name}');if(ad){adName=adName||String(ad.name??'');campaignName=campaignName||String(ad.campaign?.name??'');adsetName=adsetName||String(ad.adset?.name??'')}}catch{}}
 if(!name||!phone)return{status:'error',reason:'O lead da Meta não trouxe nome e telefone suficientes para criar o cadastro.'}
 const{data:links,error:linkError}=await supabase.from('meta_campaign_links').select('id,campaign_id,campaign_name,form_id,form_name,broker_ids,active').eq('active',true);if(linkError)throw linkError
 const link=(links??[]).find((x:any)=>campaignId&&x.campaign_id===campaignId&&(!x.form_id||x.form_id===formId))||(links??[]).find((x:any)=>formId&&x.form_id===formId); if(!link)return{status:'unlinked',reason:'Nenhuma campanha/formulário Meta ativo está vinculado no Cadena.',campaignId,formId}
 let duplicate:any=null; if(phone){const q=await supabase.from('leads').select('id,nome').eq('telefone',phone).is('deleted_at',null).limit(1).maybeSingle();duplicate=q.data} if(!duplicate&&email){const q=await supabase.from('leads').select('id,nome').eq('email',email).is('deleted_at',null).limit(1).maybeSingle();duplicate=q.data}
 let leadId=duplicate?.id??null; if(!leadId){const broker=await supabase.rpc('meta_next_broker',{p_link_id:link.id});if(broker.error)throw broker.error;const responsavelId=broker.data as string|null;const{data:created,error}=await supabase.from('leads').insert({nome:name,telefone:phone,email:email||null,origem:'Meta Ads',status:'novo',responsavel_id:responsavelId}).select('id').single();if(error)throw error;leadId=created.id;if(responsavelId)await supabase.from('activities').insert({lead_id:leadId,user_id:responsavelId,tipo:'observacao',descricao:'Lead recebido automaticamente da Meta Ads e distribuído pela roleta. Campanha: '+(campaignName||link.campaign_name)+'.'})}
 const{error:metaError}=await supabase.from('meta_leads').insert({meta_lead_id:leadgenId,lead_id:leadId,campaign_id:campaignId||link.campaign_id,campaign_name:campaignName||link.campaign_name,adset_id:adsetId||null,adset_name:adsetName||null,ad_id:adId||null,ad_name:adName||null,form_id:formId||link.form_id||null,form_name:formName||link.form_name||null,page_id:pageId||null,platform:String(leadData?.platform??'Meta'),field_data:fields,raw_payload:leadData});if(metaError&&metaError.code!=='23505')throw metaError
 return{status:duplicate?'duplicate_lead':'created',leadId,campaignId:campaignId||link.campaign_id,formId:formId||link.form_id}
}
export async function GET(request:Request){const{searchParams}=new URL(request.url);const mode=searchParams.get('hub.mode');const token=searchParams.get('hub.verify_token');const challenge=searchParams.get('hub.challenge');if(mode==='subscribe'&&token&&token===process.env.META_WEBHOOK_VERIFY_TOKEN)return new Response(challenge??'',{status:200});return NextResponse.json({error:'Verificação do webhook inválida.'},{status:403})}
export async function POST(request:Request){try{const raw=await request.text();const signature=request.headers.get('x-hub-signature-256');const secret=process.env.META_APP_SECRET;if(secret){const expected='sha256='+crypto.createHmac('sha256',secret).update(raw).digest('hex');const a=Buffer.from(signature??'');const b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return NextResponse.json({error:'Assinatura do webhook inválida.'},{status:403})}const body=JSON.parse(raw);const values:any[]=[];if(Array.isArray(body?.entries))values.push(...body.entries);else if(Array.isArray(body?.entry))for(const entry of body.entry)for(const change of entry.changes??[])values.push(change.value);else if(body?.leadgen_id||body?.id)values.push(body);if(!values.length)return NextResponse.json({ok:true,processed:0});const results=[];for(const value of values)results.push(await processLead(value));return NextResponse.json({ok:true,processed:results.length,results})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:String(error)},{status:500})}}