'use client'

import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '../../supabase-client'

type DeletedLead = { id: string; nome: string; telefone: string | null; email: string | null; deleted_at: string; deletion_reason: string | null }
type Audit = { id: string; lead_id: string; actor_id: string | null; action: string; field_name: string | null; old_value: string | null; new_value: string | null; created_at: string }
type Profile = { id: string; nome: string }

const actionLabel: Record<string, string> = { criado: 'Lead criado', responsavel_alterado: 'Responsável alterado', status_alterado: 'Status alterado', campo_alterado: 'Campo alterado', excluido: 'Lead enviado para a lixeira', restaurado: 'Lead restaurado', exclusao_fisica: 'Exclusão física' }
const formatDate = (value: string) => new Date(value).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short' })

export default function AuditoriaPage() {
  const router = useRouter(); const supabase = useMemo(() => createClient(), [])
  const [role, setRole] = useState('corretor'); const [deleted, setDeleted] = useState<DeletedLead[]>([]); const [audit, setAudit] = useState<Audit[]>([]); const [profiles, setProfiles] = useState<Profile[]>([]); const [tab, setTab] = useState<'lixeira' | 'historico'>('lixeira'); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  async function load() { const { data: { user } } = await supabase.auth.getUser(); if (!user) { router.replace('/login'); return } const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).maybeSingle(); setRole(profile?.role ?? 'corretor'); const { data: people } = await supabase.from('profiles').select('id, nome'); setProfiles((people ?? []) as Profile[]); const [{ data: deletedData }, { data: auditData }] = await Promise.all([supabase.from('leads').select('id, nome, telefone, email, deleted_at, deletion_reason').not('deleted_at', 'is', null).order('deleted_at', { ascending: false }).limit(500), supabase.from('lead_audit_log').select('id, lead_id, actor_id, action, field_name, old_value, new_value, created_at').order('created_at', { ascending: false }).limit(500)]); setDeleted((deletedData ?? []) as DeletedLead[]); setAudit((auditData ?? []) as Audit[]) }
  useEffect(() => { load() }, [])
  async function restore(id: string) { setSaving(true); setError(''); const { error } = await supabase.rpc('restore_lead', { p_lead_id: id }); if (error) setError(error.message); else await load(); setSaving(false) }
  const canManage = role === 'admin' || role === 'gerente'; const actorName = (id: string | null) => profiles.find((p) => p.id === id)?.nome ?? 'Sistema'
  if (!canManage && !error) return <div className="shell"><main className="main" style={{ marginLeft: 0, width: '100%' }}><div className="page"><div className="card"><strong>Acesso restrito</strong><p className="sub">A auditoria é exclusiva para gerente e administrador.</p></div></div></main></div>
  return <div className="shell"><aside className="sidebar"><div className="brand">CRM <span>Cadena</span></div><nav className="nav"><a href="/">Dashboard</a><a href="/#leads">Leads</a><a href="/importacao">Importar</a><a href="/followups">Follow-ups</a><a href="/kanban">Kanban</a><a className="active" href="/auditoria">Auditoria</a><a href="#">Gestão</a></nav></aside><main className="main"><header className="topbar"><strong>CRM Cadena</strong><button className="btn" onClick={async () => { await supabase.auth.signOut(); router.replace('/login') }}>Sair</button></header><div className="page"><div className="eyebrow">Controle e rastreabilidade</div><h1>Auditoria</h1><p className="sub">Veja alterações importantes e recupere leads removidos sem perder o histórico.</p>{error && <div className="form-error">{error}</div>}<div className="toolbar" style={{ marginTop: 24 }}><div className="actions"><button className={`btn ${tab === 'lixeira' ? 'primary' : ''}`} onClick={() => setTab('lixeira')}>Lixeira ({deleted.length})</button><button className={`btn ${tab === 'historico' ? 'primary' : ''}`} onClick={() => setTab('historico')}>Histórico ({audit.length})</button></div></div>{tab === 'lixeira' ? <section className="card">{deleted.length === 0 ? <div className="empty">A lixeira está vazia.</div> : <div className="table-wrap"><table><thead><tr><th>Lead</th><th>Excluído em</th><th>Motivo</th><th>Ação</th></tr></thead><tbody>{deleted.map((lead) => <tr key={lead.id}><td><strong>{lead.nome}</strong><div className="sub">{lead.telefone ?? 'Sem telefone'} · {lead.email ?? 'Sem e-mail'}</div></td><td>{formatDate(lead.deleted_at)}</td><td>{lead.deletion_reason ?? '—'}</td><td><button className="btn" disabled={saving} onClick={() => restore(lead.id)}>Restaurar</button></td></tr>)}</tbody></table></div>}</section> : <section className="card">{audit.length === 0 ? <div className="empty">Nenhuma alteração registrada.</div> : <div className="timeline">{audit.map((item) => <article className="timeline-item" key={item.id}><div><strong>{actionLabel[item.action] ?? item.action}</strong><span>{formatDate(item.created_at)}</span></div><p>Por <strong>{actorName(item.actor_id)}</strong>{item.field_name ? ` · campo: ${item.field_name}` : ''}{item.old_value || item.new_value ? ` · ${item.old_value ?? '—'} → ${item.new_value ?? '—'}` : ''}</p></article>)}</div>}</section>}</div></main></div>
}
