'use client'

import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import AppShell from '../../components/app-shell'
import { createClient } from '../../supabase-client'

type Lead={id:string;status:string;responsavel_id:string|null;origem:string|null;created_at:string}; type Profile={id:string;nome:string}
const statusLabels:Record<string,string>={novo:'Novo',em_atendimento:'Em atendimento',visita:'Visita',proposta:'Proposta',ganho:'Ganho',perdido:'Perdido'}
export default function RelatoriosPage(){const router=useRouter();const supabase=useMemo(()=>createClient(),[]);const[role,setRole]=useState('corretor');const[leads,setLeads]=useState<Lead[]>([]);const[profiles,setProfiles]=useState<Profile[]>([]);const[period,setPeriod]=useState('30');const[error,setError]=useState('');
useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const{data:p}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();setRole(p?.role??'corretor');const[{data:l},{data:people}]=await Promise.all([supabase.from('leads').select('id,status,responsavel_id,origem,created_at').is('deleted_at',null).limit(5000),supabase.from('profiles').select('id,nome').order('nome')]);setLeads((l??[]) as Lead[]);setProfiles((people??[]) as Profile[])})()},[])
const since=Date.now()-Number(period)*86400000;const scoped=leads.filter(l=>new Date(l.created_at).getTime()>=since);const total=scoped.length;const won=scoped.filter(l=>l.status==='ganho').length;const lost=scoped.filter(l=>l.status==='perdido').length;const conversion=total?Math.round(won/total*100):0;const person=(id:string|null)=>profiles.find(p=>p.id===id)?.nome??'Sem responsável';const origins=Object.entries(scoped.reduce<Record<string,number>>((a,l)=>{const k=l.origem||'Não informada';a[k]=(a[k]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]);const team=Object.entries(scoped.reduce<Record<string,number>>((a,l)=>{const k=l.responsavel_id||'none';a[k]=(a[k]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]);
return <AppShell role={role}><div className="page"><div className="eyebrow">Inteligência comercial</div><h1>Relatórios</h1><p className="sub">Indicadores da operação comercial para acompanhar volume, funil, origens e equipe.</p><div className="toolbar"><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option><option value="365">Último ano</option></select></div>{error&&<div className="form-error">{error}</div>}<section className="grid"><div className="card"><div className="metric-label">Leads recebidos</div><div className="metric">{total}</div></div><div className="card"><div className="metric-label">Ganhos</div><div className="metric">{won}</div></div><div className="card"><div className="metric-label">Perdidos</div><div className="metric">{lost}</div></div><div className="card"><div className="metric-label">Conversão em ganho</div><div className="metric">{conversion}%</div></div></section><div className="form-grid"><section className="card"><h2 className="section-title">Funil</h2>{Object.entries(statusLabels).map(([s,l])=>{const n=scoped.filter(x=>x.status===s).length;return <div className="detail-row" key={s}><span>{l}</span><strong>{n}</strong></div>})}</section><section className="card"><h2 className="section-title">Origem dos leads</h2>{origins.length?origins.map(([n,v])=><div className="detail-row" key={n}><span>{n}</span><strong>{v}</strong></div>):<div className="empty">Sem dados no período.</div>}</section></div><section className="card"><h2 className="section-title">Leads por responsável</h2>{team.length?team.map(([id,n])=><div className="detail-row" key={id}><span>{person(id==='none'?null:id)}</span><strong>{n}</strong></div>):<div className="empty">Sem dados no período.</div>}</section></div></AppShell>}
