'use client'

import { useMemo, useState } from 'react'
import { CalendarEvent, CalendarView, EventType, EVENT_TYPES } from '../../types/calendar'
import { formatDayTitle, formatMonthTitle } from '../../lib/calendar'
import { useCalendarEvents } from '../../hooks/useCalendarEvents'
import MiniCalendar from './MiniCalendar';import WeekView from './WeekView';import DayView from './DayView';import MonthView from './MonthView';import AgendaView from './AgendaView';import EventModal from './EventModal'
type Person={id:string;nome?:string|null;name?:string|null;email?:string|null;role?:string|null};type Lead={id:string;nome?:string|null;name?:string|null}
export default function CalendarShell({userId,role,userName,userEmail,profiles,leads}:{userId:string;role:string;userName:string;userEmail:string;profiles?:Person[];leads?:Lead[]}){
 const [cur,setCur]=useState(new Date()),[mini,setMini]=useState(new Date()),[view,setView]=useState<CalendarView>('week'),[typeFilters,setTypeFilters]=useState<EventType[]>(EVENT_TYPES.map(x=>x.value)),[brokerFilters,setBrokerFilters]=useState<string[]|null>(null),[modal,setModal]=useState<CalendarEvent|null|undefined>(undefined),[modalDate,setModalDate]=useState(new Date()),[toast,setToast]=useState('')
 const range=useMemo(()=>{const a=new Date(cur),b=new Date(cur);a.setDate(a.getDate()-42);b.setDate(b.getDate()+45);const ms=new Date(mini.getFullYear(),mini.getMonth(),1),me=new Date(mini.getFullYear(),mini.getMonth()+1,0);if(ms<a)a.setTime(ms.getTime());if(me>b)b.setTime(me.getTime());return {a,b}},[cur,mini]);const {events,profiles:hookProfiles,leads:hookLeads,loading,error,createEvent,updateEvent,deleteEvent}=useCalendarEvents(range.a,range.b,typeFilters,brokerFilters??[]);const people=profiles?.length?profiles:hookProfiles,leadList=leads?.length?leads:hookLeads
 const openNew=(d=new Date(cur))=>{setModalDate(d);setModal(null);setToast('')},openEdit=(e:CalendarEvent)=>{setModalDate(new Date(`${e.date}T00:00:00`));setModal(e)}
 const save=async(data:Partial<CalendarEvent>)=>{if(data.id)await updateEvent(data.id,data);else await createEvent(data);setModal(undefined);setToast('✓ Evento salvo!');setTimeout(()=>setToast(''),2500)};const remove=async(id:string)=>{await deleteEvent(id);setModal(undefined);setToast('✓ Evento excluído!');setTimeout(()=>setToast(''),2500)}
 const navigate=(n:number)=>{const d=new Date(cur);if(view==='day')d.setDate(d.getDate()+n);else if(view==='week')d.setDate(d.getDate()+n*7);else if(view==='month')d.setMonth(d.getMonth()+n);else d.setDate(d.getDate()+n*14);setCur(d);setMini(new Date(d))};const title=view==='day'?formatDayTitle(cur):view==='agenda'?`Agenda — ${formatMonthTitle(cur)}`:formatMonthTitle(cur)
 const toggleType=(t:EventType)=>setTypeFilters(x=>x.includes(t)?x.filter(v=>v!==t):[...x,t]);const toggleBroker=(id:string)=>setBrokerFilters(x=>{const all=people.map(p=>p.id);if(x===null)return all.filter(v=>v!==id);return x.includes(id)?x.filter(v=>v!==id):[...x,id]})
 return <div className="cal-shell"><aside className="cal-sidebar"><div className="cal-logo">CRM <b>Cadena</b></div><MiniCalendar date={mini} events={events} onChange={d=>{setMini(d);setCur(d)}} onMonthChange={setMini}/><section><h3>Calendários</h3>{EVENT_TYPES.map(t=><label className="cal-toggle" key={t.value}><input type="checkbox" checked={typeFilters.includes(t.value)} onChange={()=>toggleType(t.value)}/><i style={{background:t.border}}/>{t.label}</label>)}</section><section><h3>Corretores</h3>{people.length===0?<small>Nenhum corretor encontrado.</small>:people.map(p=><label className="cal-toggle" key={p.id}><input type="checkbox" checked={brokerFilters===null||brokerFilters.includes(p.id)} onChange={()=>toggleBroker(p.id)}/><i className="cal-avatar-dot">{(p.nome??p.name??p.email??'?').slice(0,1).toUpperCase()}</i><span>{p.nome??p.name??p.email}</span></label>)}</section><footer><div className="cal-user-avatar">{(userName||userEmail||'?').slice(0,1).toUpperCase()}</div><div><strong>{userName||userEmail||'Usuário'}</strong><small>{role}</small></div></footer></aside><main className="cal-main"><div className="cal-topbar"><button onClick={()=>{const d=new Date();setCur(d);setMini(d)}}>Hoje</button><button onClick={()=>navigate(-1)} aria-label="Anterior">‹</button><button onClick={()=>navigate(1)} aria-label="Próximo">›</button><h1>{title}</h1><div className="cal-tabs">{(['day','week','month','agenda'] as CalendarView[]).map(v=><button className={view===v?'active':''} key={v} onClick={()=>setView(v)}>{v==='day'?'Dia':v==='week'?'Semana':v==='month'?'Mês':'Agenda'}</button>)}</div><button className="cal-new" onClick={()=>openNew()}>+ Novo evento</button></div><div className="cal-legend">{EVENT_TYPES.map(t=><span key={t.value}><i style={{background:t.border}}/>{t.label}</span>)}</div>{loading?<div className="cal-loading">{Array.from({length:8},(_,i)=><div key={i}/>)}</div>:error?<div className="cal-error-box">{error}<button onClick={()=>window.location.reload()}>Tentar novamente</button></div>:view==='week'?<WeekView date={cur} events={events} onCreate={openNew} onEdit={openEdit}/>:view==='day'?<DayView date={cur} events={events} onCreate={openNew} onEdit={openEdit}/>:view==='month'?<MonthView date={cur} events={events} onCreate={openNew} onEdit={openEdit}/>:<AgendaView date={cur} events={events} onEdit={openEdit}/>}</main>{modal!==undefined&&<EventModal event={modal} date={modalDate} userId={userId} profiles={people} leads={leadList} onClose={()=>setModal(undefined)} onSave={save} onDelete={remove}/>} {toast&&<div className="cal-toast">{toast}</div>}</div>
}
