'use client'

import { useEffect, useState } from 'react'
import { CalendarEvent, EVENT_TYPES, EventType } from '../../types/calendar'

type Person={id:string;nome?:string|null;name?:string|null;email?:string|null;role?:string|null};type Lead={id:string;nome?:string|null;name?:string|null}
type Form={type:EventType;title:string;lead_id:string;date:string;hour:string;dur:string;corretor_id:string;notes:string}
const initial=(date:Date,uid:string):Form=>({type:'visita',title:'',lead_id:'',date:`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`,hour:'09:00',dur:'60',corretor_id:uid,notes:''})
export default function EventModal({event,date,userId,profiles,leads,onClose,onSave,onDelete}:{event:CalendarEvent|null;date:Date;userId:string;profiles:Person[];leads:Lead[];onClose:()=>void;onSave:(d:Partial<CalendarEvent>)=>Promise<void>;onDelete:(id:string)=>Promise<void>}){
 const [f,setF]=useState<Form>(initial(date,userId));const [err,setErr]=useState('');const [saving,setSaving]=useState(false)
 useEffect(()=>{if(event)setF({type:event.type,title:event.title,lead_id:event.lead_id??'',date:event.date,hour:`${String(event.hour).padStart(2,'0')}:${String(event.min).padStart(2,'0')}`,dur:String(event.dur),corretor_id:event.corretor_id??userId,notes:event.notes??''});else setF(initial(date,userId));setErr('')},[event,date,userId])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!f.title.trim()){setErr('Informe um título para o evento.');return}setSaving(true);try{await onSave({id:event?.id,type:f.type,title:f.title,lead_id:f.lead_id||undefined,date:f.date,hour:Number(f.hour.split(':')[0]),min:Number(f.hour.split(':')[1]),dur:Number(f.dur),corretor_id:f.corretor_id,corretor:profiles.find(p=>p.id===f.corretor_id)?.nome??profiles.find(p=>p.id===f.corretor_id)?.name??'',lead:leads.find(l=>l.id===f.lead_id)?.nome??leads.find(l=>l.id===f.lead_id)?.name,notes:f.notes});onClose()}catch{setErr('Não foi possível salvar o evento. Tente novamente.')}finally{setSaving(false)}}
 return <div className="cal-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="cal-modal" onSubmit={submit}><header><div><span>{event?'Editar evento':'Novo evento'}</span><h2>{event?.title??'Novo evento'}</h2></div><button type="button" onClick={onClose}>×</button></header><label>Título *<input autoFocus value={f.title} onChange={e=>setF({...f,title:e.target.value})} />{err&&<small className="cal-error">{err}</small>}</label><fieldset><legend>Tipo</legend><div className="cal-type-buttons">{EVENT_TYPES.map(t=><button type="button" key={t.value} className={f.type===t.value?'active':''} style={{background:t.bg,color:t.text,borderColor:t.border}} onClick={()=>setF({...f,type:t.value})}>{t.label}</button>)}</div></fieldset><div className="cal-form-grid"><label>Lead<select value={f.lead_id} onChange={e=>setF({...f,lead_id:e.target.value})}><option value="">Sem lead</option>{leads.map(l=><option key={l.id} value={l.id}>{l.nome??l.name}</option>)}</select></label><label>Corretor responsável<select value={f.corretor_id} onChange={e=>setF({...f,corretor_id:e.target.value})}><option value="">Sem corretor</option>{profiles.filter(p=>!p.role||p.role==='corretor'||p.role==='gerente'||p.role==='admin').map(p=><option key={p.id} value={p.id}>{p.nome??p.name??p.email}</option>)}</select></label><label>Data<input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label><label>Horário<input type="time" value={f.hour} onChange={e=>setF({...f,hour:e.target.value})}/></label></div><label>Duração<select value={f.dur} onChange={e=>setF({...f,dur:e.target.value})}><option value="30">30min</option><option value="60">1h</option><option value="90">1h30</option><option value="120">2h</option></select></label><label>Notas<textarea rows={4} value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><footer>{event&&<button type="button" className="cal-delete" disabled={saving} onClick={async()=>{setSaving(true);try{await onDelete(event.id);onClose()}catch{setErr('Não foi possível excluir o evento.')}finally{setSaving(false)}}}>Excluir evento</button>}<span/><button type="button" onClick={onClose}>Cancelar</button><button className="cal-save" disabled={saving}>{saving?'Salvando…':'Salvar evento'}</button></footer></form></div>
}
