'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import AppShell from '../../components/app-shell'
import { createClient } from '../../supabase-client'

type Lead = { id: string; nome: string; telefone: string | null; status: string; responsavel_id: string | null }
type Activity = { id: string; lead_id: string; user_id: string; tipo: string; descricao: string | null; created_at: string }
type Profile = { id: string; nome: string }
const labels: Record<string,string> = { ligacao:'Ligação', whatsapp:'WhatsApp', observacao:'Observação', visita:'Visita', status_alterado:'Status alterado' }

export default function AtendimentosPage() {
  const router = useRouter(); const supabase = useMemo(() => createClient(), [])
  const [role,setRole]=useState('corretor'); const [userId,setUserId]=useState(''); const [leads,setLeads]=useState<Lead[]>([]); const [activities,setActivities]=useState<Activity[]>([]); const [profiles,setProfiles]=useState<Profile[]>([]); const [selectedLead,setSelectedLead]=useState('todos'); const [type,setType]=useState('todos'); const [search,setSearch]=useState(''); const [text,setText]=useState(''); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
  async function load(){ const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace('/login');return} setUserId(user.id); const {data:p}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle(); setRole(p?.role??'corretor'); const [{data:l},{data:a,error:e},{data:people}]=await Promise.all([supabase.from('leads').select('id,nome,telefone,status,responsavel_id').is('deleted_at',null).order('nome').limit(2000),supabase.from('activities').select('id,lead_id,user_id,tipo,descricao,created_at').order('created_at',{ascending:false}).limit(1000),supabase.from('profiles').select('id,nome').order('nome')]); if(e)setError(e.message);setLeads((l??[]) as Lead[]);setActivities((a??[]) as Activity[]);setProfiles((people??[]) as Profile[]) }
  useEffect(()=>{load()},[])
  const leadName=(id:string)=>leads.find(l=>l.id===id)?.nome??'Lead removido'; const personName=(id:string)=>profiles.find(p=>p.id===id)?.nome??'Sistema'
  const visible=activities.filter(a=>(selectedLead==='todos'||a.lead_id===selectedLead)&&(type==='todos'||a.tipo===type)&&(!search.trim()||leadName(a.lead_id).toLowerCase().includes(search.toLowerCase())||(a.descricao??'').toLowerCase().includes(search.toLowerCase())))
  async function add(e:FormEvent){e.preventDefault();if(!selectedLead||selectedLead==='todos'||!text.trim())return;setSaving(true);setError('');const {error}=await supabase.from('activities').insert({lead_id:selectedLead,user_id:userId,tipo:type==='todos'?'observacao':type,descricao:text.trim()});if(error)setError(error.message);else{setText('');await load()}setSaving(false)}
  return <AppShell role={role}><div className="page"><div className="eyebrow">Operação comercial</div><h1>Atendimentos</h1><p className="sub">Histórico centralizado de ligações, WhatsApp, observações e visitas registradas nos leads.</p>{error&&<div className="form-error">{error}</div>}
  <section className="card"><div className="toolbar"><div><h2 className="section-title">Registrar atendimento</h2><div className="sub">Cada registro fica vinculado ao lead e ao usuário.</div></div></div><form className="activity-form" onSubmit={add}><select value={selectedLead} onChange={e=>setSelectedLead(e.target.value)}><option value="todos">Selecione o lead</option>{leads.map(l=><option key={l.id} value={l.id}>{l.nome}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="observacao">Observação</option><option value="ligacao">Ligação</option><option value="whatsapp">WhatsApp</option><option value="visita">Visita</option></select><textarea rows={3} value={text} onChange={e=>setText(e.target.value)} placeholder="O que aconteceu no atendimento?"/><button className="btn primary" disabled={saving||selectedLead==='todos'||!text.trim()}>{saving?'Salvando...':'Registrar atendimento'}</button></form></section>
  <section className="card"><div className="toolbar"><div><h2 className="section-title">Histórico operacional</h2><div className="sub">Mais recentes primeiro</div></div></div><div className="lead-filters"><input placeholder="Buscar no histórico..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={selectedLead} onChange={e=>setSelectedLead(e.target.value)}><option value="todos">Todos os leads</option>{leads.map(l=><option key={l.id} value={l.id}>{l.nome}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="todos">Todos os tipos</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>{visible.length===0?<div className="empty">Nenhum atendimento encontrado.</div>:<div className="timeline">{visible.map(a=><article className="timeline-item" key={a.id}><div><strong>{labels[a.tipo]??a.tipo} · {leadName(a.lead_id)}</strong><span>{new Date(a.created_at).toLocaleString('pt-BR')}</span></div><p>Por <strong>{personName(a.user_id)}</strong>{a.descricao?` · ${a.descricao}`:''}</p></article>)}</div>}</section></div></AppShell>
}
