'use client'

import { ReactNode, useEffect, useState } from 'react'
import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { createClient } from '../supabase-client'
import DashboardMiniKanban from './dashboard-mini-kanban'
import DashboardFunnel from './dashboard-funnel'

type Props = { children: ReactNode; role?: string; email?: string; title?: string }
type Notification = { id: string; title: string; message: string; lead_id: string | null; created_at: string }
const navGroups = [
  { key:'crm', label:'CRM', items:[['/#leads','◉','Leads'],['/atendimentos','☷','Atendimentos'],['/kanban','▦','Kanban'],['/followups','◷','Follow-ups']] },
  { key:'agenda', label:'Agenda', items:[['/calendario','▣','Calendário'],['/journal','✎','Meu Journal']] },
  { key:'operacao', label:'Operação', items:[['/importacao','⇩','Importar leads'],['/imoveis','⌂','Imóveis'],['/simulador','▤','Simulador'],['/contratos','▤','Contratos'],['/visitas','◷','Visitas'],['/propostas','✓','Propostas']] },
  { key:'gestao', label:'Gestão', items:[['/relatorios','▥','Relatórios'],['/dashboard-gerencial','▥','Dashboard Gerencial'],['/gestao','♙','Gestão da equipe'],['/integracoes/meta','◎','Meta Ads'],['/auditoria','◌','Auditoria']] }
] as const

export default function AppShell({ children, role = 'corretor', email = '', title = 'CRM Cadena' }: Props) {
  const pathname = usePathname(); const router = useRouter()
  const [darkMode,setDarkMode]=useState(false); const [collapsed,setCollapsed]=useState(false); const [hash,setHash]=useState(''); const [openGroups,setOpenGroups]=useState<Record<string,boolean>>({crm:true,agenda:true,operacao:true,gestao:true}); const [unreadNotifications,setUnreadNotifications]=useState(0); const [toast,setToast]=useState<Notification|null>(null)
  async function logout(){const supabase=createClient();await supabase.auth.signOut();router.replace('/login')}
  useEffect(()=>{const saved=window.localStorage.getItem('sidebar-collapsed');setCollapsed(saved==='true');const savedTheme=window.localStorage.getItem('theme')||window.localStorage.getItem('crm-theme');const prefers=window.matchMedia('(prefers-color-scheme: dark)').matches;const dark=savedTheme==='dark'||(!savedTheme&&prefers);setDarkMode(dark);document.documentElement.classList.toggle('dark',dark);document.documentElement.dataset.theme=dark?'dark':'light';const syncHash=()=>setHash(window.location.hash);syncHash();window.addEventListener('hashchange',syncHash);return()=>window.removeEventListener('hashchange',syncHash)},[])
  const toggleTheme=()=>setDarkMode(v=>{const next=!v;document.documentElement.classList.toggle('dark',next);document.documentElement.dataset.theme=next?'dark':'light';window.localStorage.setItem('theme',next?'dark':'light');window.localStorage.setItem('crm-theme',next?'dark':'light');return next})
  const toggleSidebar=()=>setCollapsed(v=>{const next=!v;window.localStorage.setItem('sidebar-collapsed',String(next));return next})
  const toggleGroup=(key:string)=>setOpenGroups(v=>({...v,[key]:!v[key]}));
  useEffect(()=>{let initialized=false;let lastNotificationId='';async function loadNotifications(){const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return;const[{count},{data:latest}]=await Promise.all([supabase.from('lead_notifications').select('id',{count:'exact',head:true}).eq('user_id',user.id).is('read_at',null),supabase.from('lead_notifications').select('id,title,message,lead_id,created_at').eq('user_id',user.id).is('read_at',null).order('created_at',{ascending:false}).limit(1)]);setUnreadNotifications(count??0);const notification=(latest?.[0]??null)as Notification|null;if(notification&&initialized&&notification.id!==lastNotificationId){setToast(notification);window.setTimeout(()=>setToast(current=>current?.id===notification.id?null:current),5000)}if(notification)lastNotificationId=notification.id;initialized=true}loadNotifications();const timer=window.setInterval(loadNotifications,5000);return()=>window.clearInterval(timer)},[])

async function openLeads(){const supabase=createClient();await supabase.rpc('mark_lead_notifications_read');setUnreadNotifications(0);setToast(null);router.push('/#leads')}

const showDashboardExtras=pathname==='/'
  const isActive=(href:string)=>{if(href==='/')return pathname==='/'&&hash!=='#leads';if(href==='/#leads')return pathname==='/'&&hash==='#leads';return pathname===href||pathname.startsWith(`${href}/`)}
  const avatar=(email||'U').slice(0,1).toUpperCase()
  return <div className={`shell ${collapsed?'sidebar-collapsed':''}`}>
    <aside className={`sidebar ${collapsed?'collapsed':''}`}>
      <div className="sidebar-header"><div className="brand">CRM <span>Cadena</span></div><button className="sidebar-toggle" onClick={toggleSidebar} aria-label={collapsed?'Expandir sidebar':'Recolher sidebar'}>{collapsed?'›':'‹'}</button></div>
      <nav className="nav" aria-label="Navegação principal"><div className="nav-scroll">        <Link href="/" title={collapsed?"Dashboard":undefined} className={`nav-item ${isActive("/")?"active":""}`}><span className="nav-icon" aria-hidden="true">⌂</span>{!collapsed&&<span className="nav-label">Dashboard</span>}</Link>        {navGroups.map(group=><div className="nav-group" key={group.key}>          {!collapsed&&<button type="button" className="nav-group-toggle" onClick={()=>toggleGroup(group.key)} aria-expanded={openGroups[group.key]}><span>{group.label}</span><span className="nav-group-chevron">{openGroups[group.key]?"⌄":"›"}</span></button>}          {(collapsed||openGroups[group.key])&&<div className="nav-group-items">            {group.items.map(([href,icon,label])=>href==="/#leads"?<button key={href} type="button" title={collapsed?label:undefined} className={`nav-item nav-button ${isActive(href)?"active":""}`} onClick={openLeads}><span className="nav-icon" aria-hidden="true">{icon}</span>{!collapsed&&<span className="nav-label">{label}</span>}{unreadNotifications>0&&<span className="lead-notification-badge">{unreadNotifications>99?"99+":unreadNotifications}</span>}</button>:<Link key={href} href={href} title={collapsed?label:undefined} className={`nav-item ${isActive(href)?"active":""}`}><span className="nav-icon" aria-hidden="true">{icon}</span>{!collapsed&&<span className="nav-label">{label}</span>}</Link>)}          </div>}        </div>)}      </div></nav>
      <div className="sidebar-footer"><Link href="/configuracoes" title={collapsed?'Configurações':undefined} className={`nav-item ${isActive('/configuracoes')?'active':''}`}><span className="nav-icon" aria-hidden="true">⚙</span>{!collapsed&&<span className="nav-label">Configurações</span>}</Link><button className="sidebar-logout nav-item" onClick={toggleTheme} type="button" title={collapsed?(darkMode?'Modo claro':'Modo noturno'):undefined}><span className="nav-icon" aria-hidden="true">{darkMode?'☀️':'🌙'}</span>{!collapsed&&<span className="nav-label">{darkMode?'Modo claro':'Modo noturno'}</span>}</button><button className="sidebar-logout nav-item" onClick={logout}><span className="nav-icon" aria-hidden="true">↪</span>{!collapsed&&<span className="nav-label">Sair</span>}</button></div>
    </aside>
    <main className="main"><header className="topbar"><div className="mobile-topbar-brand"><span className="mobile-brand-icon" aria-hidden="true">🏠</span><strong>CRM Cadena</strong></div><strong className="desktop-topbar-title">{title}</strong><div className="topbar-user"><button className="mobile-notification" type="button" aria-label="Notificações">🔔</button><span className="desktop-user-text">{email}{email&&role?` · ${role}`:''}</span><span className="mobile-avatar" aria-label="Usuário">{avatar}</span><button className="btn topbar-exit" onClick={logout}>Sair</button></div></header>
      {showDashboardExtras&&<style>{`.dashboard-funnel{display:none!important}.dashboard-funnel-toggle{margin-top:24px}.funnel-switch{display:flex;gap:4px;padding:4px;border:1px solid var(--border,#e5e7eb);border-radius:10px;background:var(--surface,#fff)}.funnel-switch button{border:0;background:transparent;padding:7px 12px;border-radius:7px;cursor:pointer;font:inherit}.funnel-switch button.active{background:var(--text,#111827);color:#fff}.real-funnel{display:flex;flex-direction:column;align-items:center;gap:5px;padding:12px 0 4px}.real-funnel-row{width:100%;display:flex;justify-content:center}.real-funnel-shape{min-width:34%;height:48px;display:flex;align-items:center;justify-content:space-between;padding:0 22px;border-radius:4px;clip-path:polygon(3% 0,97% 0,100% 100%,0 100%);font-weight:600;box-sizing:border-box}.real-funnel-shape strong{font-size:18px}.real-funnel-shape.blue{background:#dbeafe;color:#1e3a8a}.real-funnel-shape.amber{background:#fef3c7;color:#92400e}.real-funnel-shape.green{background:#dcfce7;color:#166534}.real-funnel-shape.red{background:#fee2e2;color:#991b1b}`}</style>}
      {children}{showDashboardExtras&&<><DashboardFunnel/><div className="dashboard-mini-kanban-slot"><DashboardMiniKanban/></div></>}</main>{toast&&<button type="button" className="lead-notification-toast" onClick={openLeads}><strong>{toast.title}</strong><span>{toast.message}</span><small>Clique para abrir os leads</small></button>}</div>
}
