'use client'
import{useEffect,useMemo,useState}from'react'
import{useRouter}from'next/navigation'
import AppShell from'../../../components/app-shell'
import{createClient}from'../../../supabase-client'
type LinkRow={id:string;campaign_id:string;campaign_name:string;form_id:string|null;form_name:string|null;ad_account_id:string|null;active:boolean;broker_ids:string[];created_at:string}
export default function MetaPage(){const router=useRouter();const supabase=useMemo(()=>createClient(),[]);const[role,setRole]=useState('corretor');const[links,setLinks]=useState<LinkRow[]>([]);const[brokers,setBrokers]=useState<{id:string;nome:string}[]>([]);const[error,setError]=useState('');const[message,setMessage]=useState('');const[saving,setSaving]=useState(false);const[form,setForm]=useState({campaign_id:'',campaign_name:'',form_id:'',form_name:'',ad_account_id:'',broker_ids:[] as string[]})
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const{data:p}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();const r=p?.role??'corretor';setRole(r);if(!['admin','gerente'].includes(r))return;const[{data:l,error:le},{data:b,error:be}]=await Promise.all([supabase.from('meta_campaign_links').select('id,campaign_id,campaign_name,form_id,form_name,ad_account_id,active,broker_ids,created_at').order('created_at',{ascending:false}),supabase.from('profiles').select('id,nome').eq('role','corretor').order('nome')]);if(le||be)setError(le?.message??be?.message??'Não foi possível carregar a integração.');setLinks((l??[])as LinkRow[]);setBrokers((b??[])as {id:string;nome:string}[])}
useEffect(()=>{load()},[])
function toggleBroker(id:string){setForm(v=>({...v,broker_ids:v.broker_ids.includes(id)?v.broker_ids.filter(x=>x!==id):[...v.broker_ids,id]}))}
async function save(e:React.FormEvent){e.preventDefault();setError('');setMessage('');if(!form.campaign_id||!form.campaign_name){setError('Informe o ID e o nome da campanha.');return}if(!form.broker_ids.length){setError('Selecione pelo menos um corretor para a roleta.');return}setSaving(true);const{data:{user}}=await supabase.auth.getUser();const{error}=await supabase.from('meta_campaign_links').insert({campaign_id:form.campaign_id.trim(),campaign_name:form.campaign_name.trim(),form_id:form.form_id.trim()||null,form_name:form.form_name.trim()||null,ad_account_id:form.ad_account_id.trim()||null,broker_ids:form.broker_ids,created_by:user?.id??null});if(error)setError(error.code==='23505'?'Essa campanha/formulário já está cadastrado.':error.message);else{setMessage('Campanha vinculada à roleta com sucesso.');setForm({campaign_id:'',campaign_name:'',form_id:'',form_name:'',ad_account_id:'',broker_ids:[]});await load()}setSaving(false)}
async function toggle(id:string,active:boolean){setError('');const{error}=await supabase.from('meta_campaign_links').update({active:!active}).eq('id',id);if(error)setError(error.message);else await load()}
async function remove(id:string){if(!window.confirm('Remover esta campanha do Cadena? Leads já recebidos não serão apagados.'))return;const{error}=await supabase.from('meta_campaign_links').delete().eq('id',id);if(error)setError(error.message);else await load()}
const name=(id:string)=>brokers.find(x=>x.id===id)?.nome??'Corretor removido'
if(!['admin','gerente'].includes(role))return <AppShell role={role}><div className="page"><section className="card"><strong>Acesso restrito</strong><p className="sub">A configuração das campanhas Meta Ads é exclusiva para administrador e gerente.</p></section></div></AppShell>
return <AppShell role={role}><div className="page"><div className="eyebrow">Integrações</div><h1>Meta Ads</h1><p className="sub">Vincule campanhas de MCMV ao Cadena. Cada novo lead recebido dessa campanha será enviado automaticamente para a roleta configurada.</p>{message&&<div className="form-success">{message}</div>}{error&&<div className="form-error">{error}</div>}
<section className="card"><h2 className="section-title">Nova campanha MCMV</h2><form className="lead-form" onSubmit={save}><div className="form-grid"><label>Nome da campanha *<input required value={form.campaign_name} onChange={e=>setForm(v=>({...v,campaign_name:e.target.value}))} placeholder="MCMV Curitiba — Setembro"/></label><label>ID da campanha *<input required value={form.campaign_id} onChange={e=>setForm(v=>({...v,campaign_id:e.target.value}))} placeholder="ID fornecido pela Meta"/></label><label>Nome do formulário<input value={form.form_name} onChange={e=>setForm(v=>({...v,form_name:e.target.value}))} placeholder="Pré-análise MCMV"/></label><label>ID do formulário<input value={form.form_id} onChange={e=>setForm(v=>({...v,form_id:e.target.value}))} placeholder="ID do formulário Meta"/></label><label>Conta de anúncios<input value={form.ad_account_id} onChange={e=>setForm(v=>({...v,ad_account_id:e.target.value}))} placeholder="ID da conta de anúncios"/></label></div><div><strong style={{fontSize:13}}>Corretores da roleta</strong><div className="broker-list">{brokers.map(b=><label className="broker-option" key={b.id}><input type="checkbox" checked={form.broker_ids.includes(b.id)} onChange={()=>toggleBroker(b.id)}/>{b.nome}</label>)}</div></div><button className="btn primary" disabled={saving}>{saving?'Salvando...':'Vincular campanha à roleta'}</button></form></section>
<section className="card"><div className="toolbar"><div><h2 className="section-title">Campanhas vinculadas</h2><div className="sub">Leads entram como “Novo”, recebem os dados de origem da Meta e são distribuídos na ordem de chegada.</div></div><span className="status blue">{links.length} configurada(s)</span></div>{links.length===0?<p className="sub">Nenhuma campanha configurada ainda.</p>:<div className="table-wrap"><table><thead><tr><th>Campanha</th><th>Formulário</th><th>Roleta</th><th>Status</th><th>Ações</th></tr></thead><tbody>{links.map(l=><tr key={l.id}><td><strong>{l.campaign_name}</strong><br/><span className="sub">ID {l.campaign_id}</span></td><td>{l.form_name||'Todos os formulários'}<br/><span className="sub">{l.form_id||'Sem ID específico'}</span></td><td>{(l.broker_ids??[]).map(name).join(', ')||'Sem corretores'}</td><td><span className={'status '+(l.active?'green':'red')}>{l.active?'Ativa':'Pausada'}</span></td><td><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn" onClick={()=>toggle(l.id,l.active)}>{l.active?'Pausar':'Ativar'}</button><button className="btn" onClick={()=>remove(l.id)}>Remover</button></div></td></tr>)}</tbody></table></div>}</section>
<section className="card"><h2 className="section-title">Status da conexão</h2><div className="sub">Webhook: <code>/api/integrations/meta/webhook</code>. A autorização e o token da Página ficam no ambiente seguro da aplicação; nunca são cadastrados no CRM.</div></section></div></AppShell>}
