'use client'

import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import * as XLSX from 'xlsx'
import AppShell from '../../components/app-shell'
import { createClient } from '../../supabase-client'

type Row = Record<string, unknown>
type Preview = { row: number; nome: string; telefone: string; email: string; origem: string; status: 'novo' | 'duplicado' | 'invalido'; motivo?: string; raw: Row }
type Profile = { id: string; nome: string; email: string; role: string }
type Lead = { id: string; nome: string; telefone: string | null; email: string | null }
const clean=(v:unknown)=>String(v??'').trim();const phone=(v:string)=>clean(v).replace(/\D/g,'');const mail=(v:string)=>clean(v).toLowerCase();
function findValue(row:Row,names:string[]){const keys=Object.keys(row);const normalized=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');const wanted=names.map(normalized);const key=keys.find(k=>wanted.includes(normalized(k)));return key?clean(row[key]):''}
export default function ImportacaoPage(){const router=useRouter();const supabase=useMemo(()=>createClient(),[]);const[userId,setUserId]=useState('');const[role,setRole]=useState('corretor');const[profiles,setProfiles]=useState<Profile[]>([]);const[rows,setRows]=useState<Preview[]>([]);const[fileName,setFileName]=useState('');const[processing,setProcessing]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');const[selected,setSelected]=useState<string[]>([]);const[strategy,setStrategy]=useState<'round_robin'|'random'|'manual'|'none'>('round_robin');
useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}setUserId(user.id);const{data:p}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();setRole(p?.role??'corretor');const{data}=await supabase.from('profiles').select('id,nome,email,role').eq('role','corretor').order('nome');setProfiles((data??[])as Profile[])})()},[])
async function parseFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setProcessing(true);setError('');setMessage('');setFileName(file.name);try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'});const sheet=workbook.Sheets[workbook.SheetNames[0]];const data=XLSX.utils.sheet_to_json<Row>(sheet,{defval:''});const{data:existing}=await supabase.from('leads').select('id,nome,telefone,email').is('deleted_at',null).limit(5000);const phones=new Set((existing??[]).map((l:Lead)=>phone(l.telefone??'')).filter(Boolean));const emails=new Set((existing??[]).map((l:Lead)=>mail(l.email??'')).filter(Boolean));const seenP=new Set<string>();const seenE=new Set<string>();const preview:Preview[]=data.map((raw,index)=>{const nome=findValue(raw,['nome','name','cliente','lead']);const telefone=findValue(raw,['telefone','phone','celular','whatsapp','fone']);const email=findValue(raw,['email','e-mail','e_mail']);const origem=findValue(raw,['origem','source','campanha','campaign']);const p=phone(telefone),m=mail(email);if(!nome)return{row:index+2,nome,telefone,email,origem,status:'invalido',motivo:'Nome ausente',raw};if(telefone&&p.length<10)return{row:index+2,nome,telefone,email,origem,status:'invalido',motivo:'Telefone inválido',raw};if((p&&(phones.has(p)||seenP.has(p)))||(m&&(emails.has(m)||seenE.has(m))))return{row:index+2,nome,telefone,email,origem,status:'duplicado',motivo:'Telefone ou e-mail já cadastrado',raw};if(p)seenP.add(p);if(m)seenE.add(m);return{row:index+2,nome,telefone,email,origem,status:'novo',raw}});setRows(preview);setMessage(`${preview.filter(r=>r.status==='novo').length} novos · ${preview.filter(r=>r.status==='duplicado').length} duplicados · ${preview.filter(r=>r.status==='invalido').length} inválidos`)}catch{setError('Não foi possível ler a planilha. Use CSV, XLS ou XLSX.')}setProcessing(false)}
function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}
async function importRows(){if(!userId||!['admin','gerente'].includes(role)){setError('Somente gerente ou administrador pode importar leads.');return}const valid=rows.filter(r=>r.status==='novo');if(!valid.length){setError('Não há leads novos para importar.');return}if(strategy!=='none'&&!selected.length){setError('Selecione pelo menos um corretor para distribuir.');return}setProcessing(true);setError('');setMessage('Importando...');const{data:batch,error:be}=await supabase.from('lead_imports').insert({uploaded_by:userId,file_name:fileName,file_type:fileName.toLowerCase().endsWith('.csv')?'csv':fileName.toLowerCase().endsWith('.xls')?'xls':'xlsx',total_rows:rows.length,imported_rows:0,duplicate_rows:rows.filter(r=>r.status==='duplicado').length,invalid_rows:rows.filter(r=>r.status==='invalido').length,status:'processando'}).select('id').single();if(be||!batch){setError(be?.message??'Falha ao criar histórico.');setProcessing(false);return}const imported:string[]=[];for(const row of valid){const{data:lead,error:le}=await supabase.from('leads').insert({nome:row.nome,telefone:row.telefone||null,email:row.email||null,origem:row.origem||null,status:'novo',criado_por:userId}).select('id').single();if(!le&&lead){imported.push(lead.id);await supabase.from('lead_import_rows').insert({import_id:batch.id,row_number:row.row,raw_data:row.raw,row_status:'importado',lead_id:lead.id})}else await supabase.from('lead_import_rows').insert({import_id:batch.id,row_number:row.row,raw_data:row.raw,row_status:'erro',error_message:le?.message??'Falha ao inserir'})}if(strategy!=='none'&&imported.length){let order=[...selected];if(strategy==='random')order=order.sort(()=>Math.random()-.5);const assignments=imported.map((leadId,i)=>({lead_id:leadId,from_user_id:null,to_user_id:order[i%order.length],batch_id:''}));const{data:dist}=await supabase.from('lead_distribution_batches').insert({created_by:userId,strategy:strategy==='round_robin'?'round_robin':'aleatoria',total_leads:imported.length,notes:`Importação ${fileName}`}).select('id').single();if(dist){const items=assignments.map(a=>({...a,batch_id:dist.id}));await supabase.from('lead_distribution_items').insert(items);for(const a of items)await supabase.from('leads').update({responsavel_id:a.to_user_id}).eq('id',a.lead_id)}}if(strategy==='manual'&&imported.length){setMessage(`${imported.length} leads importados. A distribuição manual é feita na lista de leads após a importação.`)}await supabase.from('lead_imports').update({imported_rows:imported.length,status:imported.length===valid.length?'concluido':'concluido_com_erros',completed_at:new Date().toISOString()}).eq('id',batch.id);if(strategy!=='manual')setMessage(`Importação concluída: ${imported.length} leads adicionados e distribuídos.`);setRows([]);setFileName('');setProcessing(false)}
const canImport=role==='admin'||role==='gerente';return <AppShell role={role}><div className="page"><div className="eyebrow">Entrada de leads</div><h1>Importar leads</h1><p className="sub">Envie uma planilha, confira os dados e escolha como distribuir os novos leads.</p>{!canImport?<section className="card"><strong>Acesso restrito</strong><p className="sub">A importação é exclusiva para gerente e administrador.</p></section>:<><section className="card"><div className="toolbar"><div><h2 className="section-title">1. Selecionar planilha</h2><div className="sub">CSV, XLS ou XLSX. A primeira linha deve conter os nomes das colunas.</div></div><label className="btn primary">{processing?'Lendo...':'Selecionar arquivo'}<input type="file" accept=".csv,.xls,.xlsx" onChange={parseFile} disabled={processing} hidden/></label></div>{fileName&&<div className="sub">Arquivo: <strong>{fileName}</strong></div>}</section>{rows.length>0&&<><section className="card"><div className="toolbar"><div><h2 className="section-title">2. Conferir importação</h2><div className="sub">Duplicados e inválidos não serão importados.</div></div><button className="btn primary" disabled={processing} onClick={importRows}>Importar {rows.filter(r=>r.status==='novo').length} novos</button></div>{message&&<div className="sub">{message}</div>}<div className="table-wrap"><table><thead><tr><th>Linha</th><th>Nome</th><th>Telefone</th><th>E-mail</th><th>Origem</th><th>Situação</th></tr></thead><tbody>{rows.slice(0,300).map(r=><tr key={r.row}><td>{r.row}</td><td><strong>{r.nome||'—'}</strong></td><td>{r.telefone||'—'}</td><td>{r.email||'—'}</td><td>{r.origem||'—'}</td><td><span className={`status ${r.status==='novo'?'green':r.status==='duplicado'?'amber':'red'}`}>{r.status==='novo'?'Novo':r.status==='duplicado'?'Duplicado':`Inválido · ${r.motivo}`}</span></td></tr>)}</tbody></table></div></section><section className="card"><h2 className="section-title">3. Distribuição</h2><p className="sub">Escolha como os leads novos serão entregues à equipe.</p><div className="lead-form"><label>Modo<select value={strategy} onChange={e=>setStrategy(e.target.value as typeof strategy)}><option value="round_robin">Roleta / rodízio por ordem de chegada</option><option value="random">Aleatório e equilibrado</option><option value="manual">Manual</option><option value="none">Não distribuir agora</option></select></label><div><strong style={{fontSize:13}}>Corretores participantes</strong><div className="broker-list">{profiles.map(p=><label className="broker-option" key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)}/>{p.nome}</label>)}</div></div>{strategy==='manual'&&<div className="sub">No modo manual, os leads entram sem responsável e podem ser atribuídos individualmente pela tela de Leads.</div>}</div></section></>}</>}</div></AppShell>}
